# Generated by Django 4.2.23 on 2025-11-04 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blotter_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Blotter ID')),
                ('complainant_first_name', models.CharField(blank=True, max_length=100, verbose_name='First name / Pangalan')),
                ('complainant_last_name', models.CharField(blank=True, max_length=100, verbose_name='Last name / Apelyido')),
                ('complainant_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle name / Gitnang Pangalan')),
                ('complainant_address', models.CharField(blank=True, max_length=255, verbose_name='Address / Tirahan')),
                ('complainant_suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffix (e.g., Jr, Sr, II)')),
                ('complainant_contact_number', models.CharField(blank=True, max_length=20, verbose_name='Numero ng Telepono')),
                ('date_of_incident', models.DateField(verbose_name='Petsa ng Insidente')),
                ('location_of_incident', models.CharField(max_length=255, verbose_name='Lugar ng Insidente')),
                ('incident_image', models.ImageField(blank=True, null=True, upload_to='blotter_images/', verbose_name='Larawan ng Insidente (Optional)')),
                ('incident_description', models.TextField(verbose_name='Detalye ng Insidente')),
                ('respondent_last_name', models.CharField(max_length=100, verbose_name='Apelyido ng Respondent')),
                ('respondent_first_name', models.CharField(max_length=100, verbose_name='Pangalan ng Respondent')),
                ('respondent_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Gitnang Pangalan ng Respondent')),
                ('respondent_address', models.CharField(max_length=255, verbose_name='Tirahan ng Respondent')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Summarize', 'Summarize'), ('Summon', 'Summon'), ('Mediation', 'Mediation'), ('Conciliation', 'Conciliation'), ('Repudiation', 'Repudiation'), ('Withdraw', 'Withdraw'), ('Dismiss', 'Dismiss'), ('Certified', 'Certified')], default='New', max_length=50, verbose_name='Status')),
                ('incident_type', models.CharField(choices=[('Theft', 'Theft / Pagnanakaw'), ('Physical Injury', 'Physical Injury / Pananakit'), ('Oral Defamation', 'Oral Defamation / Paninirang-puri (Salita)'), ('Slander by Deed', 'Slander by Deed / Paninirang-puri (Gawa)'), ('Threats', 'Threats / Pagbabanta'), ('Malicious Mischief', 'Malicious Mischief / Paninira ng Ari-arian'), ('Estafa / Swindling', 'Estafa / Swindling / Panloloko'), ('Trespassing', 'Trespassing'), ('Unjust Vexation', 'Unjust Vexation / Pang-aabala'), ('Public Scandal', 'Public Scandal / Eskandalo sa Publiko'), ('Noise Complaint', 'Noise Complaint / Reklamo sa Ingay'), ('Boundary Dispute', 'Boundary Dispute / Away sa Lupa'), ('Debt Collection', 'Debt Collection / Paniningil ng Utang'), ('Others', 'Others / Iba pa')], default='Others', max_length=100, verbose_name='Uri ng Insidente')),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='Case Number')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('title', models.CharField(max_length=200, verbose_name='Case Title/Subject')),
                ('description', models.TextField(verbose_name='Detailed Description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=255, verbose_name='Case Title')),
                ('incident_type', models.CharField(max_length=100, verbose_name='Incident Type')),
                ('status', models.CharField(choices=[('New', 'New'), ('Summarize', 'Summarize'), ('Summon', 'Summon'), ('Mediation', 'Mediation'), ('Conciliation', 'Conciliation'), ('Repudiation', 'Repudiation'), ('Withdraw', 'Withdraw'), ('Dismiss', 'Dismiss'), ('Certified', 'Certified')], max_length=50, verbose_name='Status')),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, choices=[('Settled', 'Settled'), ('Unsettled', 'Unsettled')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks/Details of Action')),
                ('amicable_settlement_date', models.DateField(blank=True, null=True)),
                ('agreement_details', models.TextField(blank=True, null=True, verbose_name='Amicable Settlement Agreement Details')),
            ],
            options={
                'ordering': ['-date_processed'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_first_name', models.CharField(blank=True, max_length=100, verbose_name='First name / Pangalan')),
                ('complainant_last_name', models.CharField(blank=True, max_length=100, verbose_name='Last name / Apelyido')),
                ('complainant_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle name / Gitnang Pangalan')),
                ('complainant_address', models.CharField(blank=True, max_length=255, verbose_name='Address / Tirahan')),
                ('complainant_suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffix (e.g., Jr, Sr, II)')),
                ('complainant_contact_number', models.CharField(blank=True, max_length=20, verbose_name='Numero ng Telepono')),
                ('informant_contact_number', models.CharField(max_length=20, verbose_name='Numero ng Telepono')),
                ('date_of_incident', models.DateField(verbose_name='Petsa ng Pangyayari')),
                ('location_of_incident', models.CharField(max_length=255, verbose_name='Lugar ng Pangyayari')),
                ('report_details', models.TextField(verbose_name='Detalye ng Ulat')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Verification', 'Under Verification'), ('Action Taken', 'Action Taken'), ('Resolved', 'Resolved'), ('Archived', 'Archived')], default='New', max_length=50, verbose_name='Status')),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(max_length=50)),
                ('appearance_date', models.DateField()),
                ('appearance_time', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cases.blotter')),
            ],
            options={
                'ordering': ['-appearance_date', '-appearance_time'],
            },
        ),
    ]
