# Generated by Django 4.2.23 on 2025-11-04 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luponschedule',
            name='lupon_member',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='luponavailability',
            name='lupon_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='system_settings.luponmember'),
        ),
        migrations.AlterUniqueTogether(
            name='luponschedule',
            unique_together={('lupon_member', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='luponavailability',
            unique_together={('lupon_member', 'day_of_week')},
        ),
    ]
